# Generated by Django 6.1.1 on 2026-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(default='Disponível', max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
